aarch64:
	aarch64-linux-gnu-gcc -static -o helloworld helloworld.c
arm:
	arm-none-linux-gnueabihf-gcc -static -o helloworld helloworld.c
x86_64:
	x86_64-unknown-linux-gnu-gcc -static -o helloworld helloworld.c
clean:
	echo "clean all"
	rm -f helloworld
